name: logging
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.12.1
    container_name: filebeat_debug
    user: root
    volumes:
      - ./debug_filebeat.yml:/usr/share/filebeat/filebeat.yml
      - logs_volume:/app/logs:ro
    command: "filebeat -e -strict.perms=false"
    networks:
      - app_network
    depends_on:
      - logstash

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash_debug
    networks:
      - app_network
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - opensearch
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
    ports:
      - "5044:5044"   # Filebeat -> Logstash
      - "9601:9600"   # Logstash monitoring

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch_debug
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Aloha.32bit
    ports:
      - "9200:9200" # OpenSearch API
      - "9600:9600" # Performans izleme
    networks:
      - app_network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
      - SERVER_HOST=0.0.0.0
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Aloha.32bit
    ports:
      - "5601:5601" # OpenSearch Dashboards web arayüzü
    networks:
      - app_network
    depends_on:
      - opensearch

networks:
  app_network:
    driver: bridge
    external: true

volumes:
  logs_volume: