filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/*.json
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: [ "logstash:5044" ]

setup.ilm.enabled: false
setup.template.enabled: false

setup.kibana:
  host: "https://opensearch-dashboards:5601"
  username: "admin"
  password: "Aloha.32bit"
  ssl:
    verification_mode: none

logging.level: info