name: engine-cluster
services:
  rate-distribution-engine:
    image: luieitalian/rate-distribution-engine
    container_name: rate-distribution-engine
    networks:
      - network
    volumes:
      - engine_logs_volume:/app/logs
      - ./subscribers:/app/subscribers
      - ./rate_calculators:/app/rate_calculators
      - ./application-config.yaml:/app/application.yaml
    depends_on:
      rest-platform:
        condition: service_started
      tcp-platform:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: debug
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APP_RATE_CALCULATION_STRATEGY: JAVASCRIPT
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      TCP_SUBSCRIBER_ENABLED: false
      REST_SUBSCRIBER_ENABLED: false

  tcp-platform:
    image: luieitalian/tcp-platform-standalone
    container_name: tcp-platform-standalone
    volumes:
      - ./initial_data_tcp.json:/app/initial_data.json:ro
    networks:
      - network
    environment:
      TCP_SERVER_USER: client
      TCP_SERVER_PASSWORD: 2345
      TCP_SIMULATOR_UPDATE_INTERVAL: 2000
      TCP_SERVER_TOTAL_STREAMS: 100
      TCP_SERVER_STREAM_INTERVAL: 2100
      APPLICATION_PROFILE: prod
      SIMULATOR_ENABLED: true
      SIMULATOR_INTENSITY: med
    ports:
      - "2000:8080"

  rest-platform:
    image: luieitalian/rest-platform
    container_name: rest-platform
    volumes:
      - ./initial_data_rest.json:/app/initial_data.json:ro
    networks:
      - network
    environment:
      REST_SERVER_USER: client
      REST_SERVER_PASSWORD: 1234
      REST_REQUEST_LIMIT: 100
      SPRING_PROFILES_ACTIVE: prod
      SIMULATOR_ENABLED: true
      SIMULATOR_INTENSITY: med
    ports:
      - "1000:8080"

networks:
  network:
    driver: bridge

volumes:
  engine_logs_volume:
