coordinator:
  subscribers:
    - name: Bloomberg_Rest
      enabled: true
      configName: bloomberg_rest-debug
      classPath: com.berkepite.MainApplication32Bit.subscribers
      className: BloombergRestSubscriber
    - name: CNN_TCP
      enabled: true
      configName: cnn_tcp-debug
      classPath: com.berkepite.MainApplication32Bit.subscribers
      className: CNNTCPSubscriber
  rates: { USD_TRY, EUR_USD, GBP_USD }
