coordinator:
  subscribers:
    - name: Bloomberg_Rest
      enabled: true
      configName: bloomberg_rest
    - name: Haberturk_Rest
      enabled: true
      configName: haberturk_rest
    - name: CNN_TCP
      enabled: true
      configName: cnn_tcp
  rates: { USD_TRY, USD_EUR, USD_GBP }